---
title: R可视化：用户生存分析
author: xiebro
date: '2024-02-25'
slug: survival-analysis
categories:
  - R可视化
tags:
  - R可视化
  - 生存分析

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
```

***Kaplan-Meier***生存分析：探索客户的生存概率随时间的变化，并可视化生存曲线，显示客户在不同时间点的**生存概率**。

数据集下载：[Telco-Customer-Churn.csv](datasets/Telco-Customer-Churn.csv)

### 数据集概览
```{r}
library(tidyverse)
dat <- 
  read.csv("datasets/Telco-Customer-Churn.csv") %>% 
  mutate(churn = if_else(Churn == "Yes", 1L, 0L))

dat %>%  glimpse()
```


### 生存分析
#### 1. 初步探查，整体生存趋势
```{r}
library(survival) # 进行生存分析的函数和工具
library(survminer) # 用于生存分析结果的可视化
library(hrbrthemes) # 用于设置可视化主题

# Kaplan-Meier Analysis
km_fit <- survfit(Surv(tenure, churn) ~ 1, data = dat)

km_fit %>% 
  ggsurvplot(
    data     = dat,
    linetype = "solid",
    conf.int = FALSE,
    ggtheme  = theme_ipsum(),
    xlab = "Time",
    ylab = "Surv. Prob"
  )
```

#### 2. 维度探查，不同特征人群的生存趋势
封装函数，方便多次画图使用
```{r}
pals <- rownames(RColorBrewer::brewer.pal.info)

sc <- . %>%
  ggsurvplot(
    data     = dat,
    linetype = "solid",
    conf.int = FALSE,
    pval     = TRUE,
    censor   = FALSE,
    palette  = sample(pals, 1),
    ggtheme  = theme_ipsum(),
    break.time.by = 14,
    xlab = "Time",
    ylab = "Surv. Prob"
  )
```
- by gender:
```{r}
gender_fit <- survfit(Surv(tenure, churn) ~ gender, data = dat)
sc(gender_fit)
```

- by PaymentMethod:
```{r}
payment_method <- survfit(Surv(tenure, churn) ~ PaymentMethod, data = dat)
sc(payment_method)
```

#### 3. 使用迭代法快速扫描维度
```{r}
library(gridExtra)

# 需要扫描的维度
cols <-
  c(
    "PhoneService",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies"
  )

plots <- 
  cols %>% 
  # 这里引入了meta programming的编程思想，用函数生成函数
  map_chr( ~ sprintf("survfit(Surv(tenure, churn) ~ %s, data = dat)", .x)) %>% 
  map(~ eval(parse(text = .))) %>% 
  map(sc) %>% 
  # 从ggsurvplot对象中提取图片
  map(pluck, "plot")

do.call(grid.arrange, plots)
```






